"""
roof_generator.py — Generative roof synthesis engine
====================================================
Replaces the default slab-only roof stage with a footprint-aware,
style-diverse, procedurally generative roof module.

Supported styles
----------------
  gable, cross-gable, hip, pyramid, dutch-gable, gambrel, mansard,
  saltbox, butterfly, skillion, flat-modern
(legacy styles "flat", "split-level", "mono-pitch", "shed" continue to
be handled by builder.py's original code path)

Key ideas
---------
1. FOOTPRINT EXTRACTION — the union of detected wall boxes is closed
   into a filled orthogonal polygon; wings are recovered by greedy
   maximal-rectangle decomposition, so cross-gables / hips follow the
   actual L / T / U plan shape instead of a naive mid-X split.

2. DISTANCE-FIELD HIP SURFACE — for hip / pyramid / mansard / dutch
   roofs the height of every roof point is  d(p, boundary) * tan(pitch)
   (optionally capped).  This is mathematically the straight-skeleton
   hip roof: ridges, hips and valleys emerge automatically for ANY
   footprint shape, including concave L/T/U plans.

3. PROFILE PRISMS — gable / gambrel / saltbox wings are generated by
   sweeping a parametric cross-section profile along each wing's ridge
   axis, with proper eave + rake overhangs and gable-end infill walls.

4. CONTROLLED RANDOMNESS — every call may take a seed; pitch, overhang,
   ridge offsets, material palette, dormers, chimneys and skylights are
   jittered inside architecturally valid ranges, so identical floor
   plans still yield distinct-but-plausible roofs.

All meshes are returned in the builder's model space
(x/y metres, z-up, wall top at z = wall_h).
"""

import numpy as np
import trimesh
from shapely.geometry import Polygon, Point, box as shp_box, MultiPolygon
from shapely.ops import unary_union

# ────────────────────────────────────────────────────────────────────
#  MATERIAL PALETTES  (RGBA)
# ────────────────────────────────────────────────────────────────────
ROOF_MATERIALS = {
    "terracotta":     [178,  86,  56, 255],
    "clay-brown":     [150,  88,  60, 255],
    "asphalt-dark":   [ 62,  62,  68, 255],
    "asphalt-gray":   [ 96,  98, 104, 255],
    "slate-blue":     [ 72,  82,  98, 255],
    "metal-seam":     [122, 128, 134, 255],
    "metal-green":    [ 74, 104,  84, 255],
    "metal-red":      [140,  52,  48, 255],
    "cedar-shake":    [138, 108,  78, 255],
    "membrane-white": [225, 223, 216, 255],
    "matte-black":    [ 40,  40,  44, 255],
    "solar-black":    [ 30,  34,  46, 255],
    "green-roof":     [104, 128,  74, 255],
}
WALL_COLOR    = [245, 242, 230, 255]
FASCIA_COLOR  = [235, 232, 224, 255]
CHIMNEY_COLOR = [156, 118,  98, 255]
GLASS_COLOR   = [150, 190, 210, 200]
PARAPET_COLOR = [ 80,  85,  90, 255]
POST_COLOR    = [ 92,  74,  56, 255]   # dark timber support pillars
SOFFIT_COLOR  = [176, 140, 102, 255]   # warm timber ceiling under roof planes

# style → materials that are architecturally plausible for it
STYLE_MATERIALS = {
    "gable":       ["asphalt-dark", "asphalt-gray", "terracotta", "metal-seam", "cedar-shake", "metal-red", "matte-black"],
    "cross-gable": ["asphalt-dark", "asphalt-gray", "terracotta", "slate-blue", "cedar-shake"],
    "hip":         ["terracotta", "clay-brown", "asphalt-dark", "slate-blue", "asphalt-gray"],
    "pyramid":     ["terracotta", "slate-blue", "asphalt-dark", "metal-seam"],
    "dutch-gable": ["terracotta", "clay-brown", "asphalt-dark", "cedar-shake"],
    "gambrel":     ["asphalt-dark", "asphalt-gray", "cedar-shake", "metal-red"],
    "mansard":     ["slate-blue", "asphalt-dark", "asphalt-gray"],
    "saltbox":     ["cedar-shake", "asphalt-dark", "asphalt-gray", "metal-seam"],
    "butterfly":   ["metal-seam", "membrane-white", "metal-green"],
    "skillion":    ["metal-seam", "metal-green", "metal-red", "membrane-white", "matte-black", "solar-black"],
    "flat-modern": ["membrane-white", "metal-seam", "asphalt-gray", "matte-black", "green-roof"],
}

NEW_ENGINE_STYLES = list(STYLE_MATERIALS.keys()) + ["composite"]


# ════════════════════════════════════════════════════════════════════
#  1. FOOTPRINT EXTRACTION
# ════════════════════════════════════════════════════════════════════
def extract_footprint(walls, scale=0.01):
    """Union all wall boxes and close them into a filled polygon.
    Robust to detection gaps: wall boxes from YOLO rarely touch
    perfectly, so we close the union with progressively larger
    morphological radii until it forms one connected outline."""
    boxes = []
    for w in walls:
        cx, cy = w["pos"][0] * scale, w["pos"][1] * scale
        ww, hh = w["w"] * scale, w["h"] * scale
        boxes.append(shp_box(cx - ww / 2, cy - hh / 2, cx + ww / 2, cy + hh / 2))
    if not boxes:
        return None
    raw = unary_union(boxes)
    total_area = sum(b.area for b in boxes)
    merged = None
    for r in (0.20, 0.45, 0.80, 1.30):
        closed = raw.buffer(r, join_style=2).buffer(-r, join_style=2)
        if isinstance(closed, MultiPolygon):
            largest = max(closed.geoms, key=lambda g: g.area)
            # accept only if the fragment clearly dominates
            if largest.area > 0.85 * sum(g.area for g in closed.geoms):
                merged = largest
                break
        else:
            merged = closed
            break
    if merged is None:  # still fragmented → take the largest piece
        closed = raw.buffer(1.3, join_style=2).buffer(-1.3, join_style=2)
        merged = max(closed.geoms, key=lambda g: g.area) \
            if isinstance(closed, MultiPolygon) else closed
    # fill interior holes (wall boxes form a ring; we want the filled plan)
    filled = Polygon(merged.exterior)
    filled = filled.simplify(0.12, preserve_topology=True)
    # snap to an orthogonal-ish polygon by rounding coords
    snapped = Polygon([(round(x, 1), round(y, 1)) for x, y in filled.exterior.coords])
    if not snapped.is_valid or snapped.area < 1.0:
        snapped = filled if filled.is_valid else filled.buffer(0)
    # sanity: the filled plan must cover at least the wall material itself
    if snapped.area < total_area:
        snapped = Polygon(raw.convex_hull.exterior)
    return snapped


def footprint_metrics(poly):
    minx, miny, maxx, maxy = poly.bounds
    w, h = maxx - minx, maxy - miny
    hull = poly.convex_hull
    return {
        "width": w, "depth": h,
        "aspect": max(w, h) / max(min(w, h), 1e-6),
        "area": poly.area,
        "convexity": poly.area / max(hull.area, 1e-6),   # <0.9 → L/T/U shape
        "bounds": (minx, miny, maxx, maxy),
    }


def decompose_wings(poly, max_wings=3, min_area_frac=0.12):
    """Greedy maximal-rectangle decomposition of an orthogonal polygon.
    Returns a list of (minx, miny, maxx, maxy) wing rectangles."""
    xs = sorted({round(x, 1) for x, _ in poly.exterior.coords})
    ys = sorted({round(y, 1) for _, y in poly.exterior.coords})
    # occupancy grid over the coordinate lattice
    cells = {}
    for i in range(len(xs) - 1):
        for j in range(len(ys) - 1):
            cx, cy = (xs[i] + xs[i + 1]) / 2, (ys[j] + ys[j + 1]) / 2
            cells[(i, j)] = poly.buffer(0.05).contains(Point(cx, cy))

    def rect_area(i0, j0, i1, j1):
        return (xs[i1 + 1] - xs[i0]) * (ys[j1 + 1] - ys[j0])

    wings, remaining = [], dict(cells)
    for _ in range(max_wings):
        best, best_a = None, 0.0
        n, m = len(xs) - 1, len(ys) - 1
        for i0 in range(n):
            for j0 in range(m):
                if not remaining.get((i0, j0)):
                    continue
                i1 = i0
                while i1 + 1 < n and remaining.get((i1 + 1, j0)):
                    i1 += 1
                for ii1 in range(i0, i1 + 1):
                    j1 = j0
                    while j1 + 1 < m and all(remaining.get((k, j1 + 1))
                                             for k in range(i0, ii1 + 1)):
                        j1 += 1
                    a = rect_area(i0, j0, ii1, j1)
                    if a > best_a:
                        best_a, best = a, (i0, j0, ii1, j1)
        if best is None or best_a < poly.area * min_area_frac:
            break
        i0, j0, i1, j1 = best
        wings.append((xs[i0], ys[j0], xs[i1 + 1], ys[j1 + 1]))
        for k in range(i0, i1 + 1):
            for l in range(j0, j1 + 1):
                remaining[(k, l)] = False
        if not any(remaining.values()):
            break
    if not wings:
        wings = [poly.bounds]
    return wings


# ════════════════════════════════════════════════════════════════════
#  2. MESH HELPERS
# ════════════════════════════════════════════════════════════════════
def _colored(mesh, rgba):
    mesh.visual.face_colors = rgba
    return mesh


def _heightfield_roof(poly, height_fn, base_z, fascia=0.14, color=None,
                      max_edge=0.45):
    """Solid roof whose top surface z = base_z + fascia + height_fn(x, y).
    Bottom is flat at base_z; the rim is closed. Works for any polygon."""
    area_constraint = (max_edge ** 2) / 2.0
    try:
        v2, faces = trimesh.creation.triangulate_polygon(
            poly, triangle_args=f"pq30a{area_constraint:.4f}", engine="triangle")
    except Exception:
        v2, faces = trimesh.creation.triangulate_polygon(poly)
    v2 = np.asarray(v2, dtype=float)
    faces = np.asarray(faces, dtype=np.int64)

    ztop = np.array([base_z + fascia + max(0.0, height_fn(x, y)) for x, y in v2])
    top = np.column_stack([v2, ztop])
    bot = np.column_stack([v2, np.full(len(v2), base_z)])

    nv = len(v2)
    verts = np.vstack([top, bot])
    f_top = faces
    f_bot = faces[:, ::-1] + nv

    # boundary edges (appear in exactly one triangle) → side band
    edges = {}
    for tri in faces:
        for a, b in ((tri[0], tri[1]), (tri[1], tri[2]), (tri[2], tri[0])):
            key = (min(a, b), max(a, b))
            edges[key] = edges.get(key, 0) + 1
    side = []
    for tri in faces:
        for a, b in ((tri[0], tri[1]), (tri[1], tri[2]), (tri[2], tri[0])):
            if edges[(min(a, b), max(a, b))] == 1:
                side.append([a, b, b + nv])
                side.append([a, b + nv, a + nv])
    mesh = trimesh.Trimesh(vertices=verts,
                           faces=np.vstack([f_top, f_bot, np.array(side)]),
                           process=True)
    if color is not None:
        _colored(mesh, color)
    return mesh


def _dist_to_boundary(poly):
    bnd = poly.boundary
    return lambda x, y: bnd.distance(Point(x, y))


def _prism_from_profile(profile_xy, length, color):
    """Extrude a closed 2D cross-section (in local X-Z) along local Y."""
    prof = Polygon(profile_xy)
    mesh = trimesh.creation.extrude_polygon(prof, height=length)
    # extrude goes along +Z of profile plane; re-map: profile X→X, profile Y→Z, extrusion→Y
    T = np.array([[1, 0, 0, 0],
                  [0, 0, 1, 0],
                  [0, 1, 0, 0],
                  [0, 0, 0, 1]], dtype=float)
    mesh.apply_transform(T)
    # multibody=False is correct here — an extruded prism is one body by
    # construction — and it is also load-bearing for deployment: leaving it
    # to trimesh calls Trimesh.body_count, which goes through
    # scipy.sparse.csgraph. scipy is 114 MB uncompressed and would push the
    # serverless bundle from 149 MB to 264 MB, past the 250 MB limit.
    mesh.fix_normals(multibody=False)
    return _colored(mesh, color)


def _place_wing_prism(mesh, rect, along_x, base_z):
    """Move a profile prism (built around origin) onto its wing rectangle.
    NOTE: _prism_from_profile extrudes the ridge along local +Y, so a
    ridge that must run along X needs the 90° turn (was inverted before,
    which rotated every gable/saltbox/gambrel wing by 90°)."""
    x0, y0, x1, y1 = rect
    cx, cy = (x0 + x1) / 2, (y0 + y1) / 2
    if along_x:  # native ridge is along Y → rotate onto X
        mesh.apply_transform(
            trimesh.transformations.rotation_matrix(np.pi / 2, [0, 0, 1]))
    mesh.apply_translation([cx, cy, base_z])
    return mesh


# ════════════════════════════════════════════════════════════════════
#  3. STYLE GENERATORS
# ════════════════════════════════════════════════════════════════════
def _gable_profile(span, rise, fascia, ridge_shift=0.0):
    """Closed pentagon cross-section of a gable roof slab."""
    hw = span / 2
    apex_x = ridge_shift * hw
    return [(-hw, 0), (hw, 0), (hw, fascia), (apex_x, rise + fascia), (-hw, fascia)]


def _gambrel_profile(span, rise, fascia, break_frac=0.62, lower_frac=0.72):
    hw = span / 2
    bx = hw * (1 - break_frac * 0.55)
    bz = rise * lower_frac
    return [(-hw, 0), (hw, 0), (hw, fascia),
            (bx, bz + fascia), (0, rise + fascia), (-bx, bz + fascia),
            (-hw, fascia)]


def _gable_end_wall(rect, along_x, rise, base_z, ridge_shift=0.0, thick=0.14):
    """Triangular infill walls under the gable at both wing ends."""
    x0, y0, x1, y1 = rect
    parts = []
    if along_x:
        span = y1 - y0
        ends = [x0 + thick / 2, x1 - thick / 2]
        for ex in ends:
            tri = Polygon([(y0, 0), (y1, 0),
                           ((y0 + y1) / 2 + ridge_shift * span / 2, rise)])
            m = trimesh.creation.extrude_polygon(tri, height=thick)
            T = np.array([[0, 0, 1, 0], [1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 0, 1]], float)
            m.apply_transform(T)
            m.apply_translation([ex - thick / 2, 0, base_z])
            parts.append(_colored(m, WALL_COLOR))
    else:
        span = x1 - x0
        ends = [y0 + thick / 2, y1 - thick / 2]
        for ey in ends:
            tri = Polygon([(x0, 0), (x1, 0),
                           ((x0 + x1) / 2 + ridge_shift * span / 2, rise)])
            m = trimesh.creation.extrude_polygon(tri, height=thick)
            T = np.array([[1, 0, 0, 0], [0, 0, 1, 0], [0, 1, 0, 0], [0, 0, 0, 1]], float)
            m.apply_transform(T)
            m.apply_translation([0, ey - thick / 2, base_z])
            parts.append(_colored(m, WALL_COLOR))
    return parts


def gen_gable_wing(rect, base_z, pitch, overhang, color,
                   ridge_shift=0.0, profile="gable", fascia=0.14):
    """One gabled (or gambrel / saltbox) wing over a rectangle."""
    x0, y0, x1, y1 = rect
    w, d = x1 - x0, y1 - y0
    along_x = w >= d                       # ridge along the longer axis
    span = (d if along_x else w) + 2 * overhang
    length = (w if along_x else d) + 2 * overhang
    rise = (span / 2) * np.tan(np.radians(pitch))

    if profile == "gambrel":
        prof = _gambrel_profile(span, rise * 1.25, fascia)
    else:
        prof = _gable_profile(span, rise, fascia, ridge_shift)

    prism = _prism_from_profile(prof, length, color)
    prism.apply_translation([0, -length / 2, 0])
    parts = [_place_wing_prism(prism, rect, along_x, base_z)]
    parts += _gable_end_wall(rect, along_x, rise * (1.25 if profile == "gambrel" else 1.0),
                             base_z, ridge_shift)
    ridge_h = rise * (1.25 if profile == "gambrel" else 1.0) + fascia
    return parts, ridge_h


def gen_hip(poly, base_z, pitch, overhang, color, cap=None, fascia=0.14):
    p = poly.buffer(overhang, join_style=2)
    dist = _dist_to_boundary(p)
    t = np.tan(np.radians(pitch))
    fn = (lambda x, y: min(dist(x, y) * t, cap)) if cap else \
         (lambda x, y: dist(x, y) * t)
    return [_heightfield_roof(p, fn, base_z, fascia, color)]


def gen_mansard(poly, base_z, color, lower_pitch=68, cap_frac=0.30, fascia=0.10):
    p = poly.buffer(0.25, join_style=2)
    m = footprint_metrics(p)
    cap = min(m["width"], m["depth"]) * cap_frac * np.tan(np.radians(lower_pitch)) * 0.18
    cap = float(np.clip(cap, 1.4, 2.6))
    dist = _dist_to_boundary(p)
    t = np.tan(np.radians(lower_pitch))
    parts = gen_hip(poly, base_z, lower_pitch, 0.25, color, cap=cap, fascia=fascia)
    # decorative cornice at the eave line
    try:
        ring = p.difference(p.buffer(-0.18, join_style=2))
        cor = trimesh.creation.extrude_polygon(ring, height=0.22)
        cor.apply_translation([0, 0, base_z - 0.05])
        parts.append(_colored(cor, FASCIA_COLOR))
    except Exception:
        pass
    return parts


def gen_dutch_gable(poly, base_z, pitch, overhang, color, fascia=0.14):
    """Hip roof with a small gable perched on the ridge."""
    m = footprint_metrics(poly)
    cap = (min(m["width"], m["depth"]) / 2 + overhang) * np.tan(np.radians(pitch)) * 0.62
    parts = gen_hip(poly, base_z, pitch, overhang, color, cap=cap, fascia=fascia)
    # gablet: small gable prism sitting at the flat ridge platform
    x0, y0, x1, y1 = m["bounds"]
    along_x = m["width"] >= m["depth"]
    shrink = cap / np.tan(np.radians(pitch))
    gx0, gy0 = x0 + shrink, y0 + shrink
    gx1, gy1 = x1 - shrink, y1 - shrink
    if gx1 - gx0 > 0.8 and gy1 - gy0 > 0.8:
        g_parts, _ = gen_gable_wing((gx0, gy0, gx1, gy1),
                                    base_z + fascia + cap - 0.03,
                                    pitch, 0.22, color, fascia=0.10)
        parts += g_parts
    return parts


def gen_butterfly(poly, base_z, pitch, overhang, color, fascia=0.16):
    """Two planes tilting DOWN toward a central valley."""
    p = poly.buffer(overhang, join_style=2)
    x0, y0, x1, y1 = p.bounds
    along_x = (x1 - x0) >= (y1 - y0)
    t = np.tan(np.radians(pitch))
    if along_x:
        mid = (y0 + y1) / 2
        fn = lambda x, y: (abs(y - mid)) * t + 0.15
    else:
        mid = (x0 + x1) / 2
        fn = lambda x, y: (abs(x - mid)) * t + 0.15
    parts = [_heightfield_roof(p, fn, base_z, fascia, color)]
    # slim fascia band emphasising the V silhouette
    try:
        ring = p.difference(p.buffer(-0.12, join_style=2))
        band = trimesh.creation.extrude_polygon(ring, height=0.30)
        band.apply_translation([0, 0, base_z + fascia +
                                ((y1 - y0) if along_x else (x1 - x0)) / 2 * t - 0.05])
    except Exception:
        pass
    return parts


def _post(x, y, z_top, size=0.17, color=POST_COLOR):
    """One square support pillar from the ground to the roof underside."""
    h = max(z_top, 0.3)
    p = trimesh.creation.box(extents=(size, size, h))
    p.apply_translation([x, y, h / 2])
    return _colored(p, color)


def _posts_along_edge(p, edge, z_top, footprint=None, inset=0.24,
                      max_spacing=3.2):
    """Support pillars under one edge of a roof polygon `p`.
    `edge` is a concrete '+x'/'-x'/'+y'/'-y' side of its bounds.
    Posts that would land inside the building interior are skipped —
    walls already carry the roof there; only floating overhangs, raised
    clerestory planes and porch bays get visible structure."""
    x0, y0, x1, y1 = p.bounds
    if edge in ("+x", "-x"):
        e = x1 - inset if edge == "+x" else x0 + inset
        lo, hi = y0 + inset, y1 - inset
        if hi <= lo:
            return []
        n = max(2, int(np.ceil((hi - lo) / max_spacing)) + 1)
        pts = [(e, lo + i * (hi - lo) / (n - 1)) for i in range(n)]
    else:
        e = y1 - inset if edge == "+y" else y0 + inset
        lo, hi = x0 + inset, x1 - inset
        if hi <= lo:
            return []
        n = max(2, int(np.ceil((hi - lo) / max_spacing)) + 1)
        pts = [(lo + i * (hi - lo) / (n - 1), e) for i in range(n)]
    parts = []
    for px, py in pts:
        if footprint is not None and \
                footprint.buffer(-0.15).contains(Point(px, py)):
            continue
        if not p.buffer(0.05).contains(Point(px, py)):
            continue
        parts.append(_post(px, py, z_top))
    return parts


def _soffit_plate(p, z_bottom, thick=0.07, color=SOFFIT_COLOR):
    """Finished ceiling layer just under a roof slab, so overhangs and
    raised planes read as built structure instead of a hollow shell."""
    try:
        plate = trimesh.creation.extrude_polygon(
            p.buffer(-0.03, join_style=2), height=thick)
        plate.apply_translation([0, 0, z_bottom - thick])
        return [_colored(plate, color)]
    except Exception:
        return []


def _directional_extend(p, edge, depth):
    """Grow a roof polygon past one side — a covered porch/verandah bay."""
    x0, y0, x1, y1 = p.bounds
    if edge == "+x":
        ext = shp_box(x1 - 0.1, y0, x1 + depth, y1)
    elif edge == "-x":
        ext = shp_box(x0 - depth, y0, x0 + 0.1, y1)
    elif edge == "+y":
        ext = shp_box(x0, y1 - 0.1, x1, y1 + depth)
    else:
        ext = shp_box(x0, y0 - depth, x1, y0 + 0.1)
    return p.union(ext)


def gen_skillion(poly, base_z, pitch, overhang, color, fascia=0.18, rng=None):
    rng = rng or np.random.default_rng()
    direction = str(rng.choice(["+x", "-x", "+y", "-y"]))
    return gen_skillion_directed(poly, base_z, pitch, overhang, color,
                                 direction, fascia, footprint=poly)


def gen_flat_modern(poly, base_z, color, parapet_h=0.55, overhang=0.35):
    p = poly.buffer(overhang, join_style=2)
    parts = [_colored(trimesh.creation.extrude_polygon(p, height=0.20), color)]
    parts[0].apply_translation([0, 0, base_z])
    try:
        ring = p.difference(p.buffer(-0.22, join_style=2))
        par = trimesh.creation.extrude_polygon(ring, height=parapet_h)
        par.apply_translation([0, 0, base_z + 0.20])
        parts.append(_colored(par, PARAPET_COLOR))
    except Exception:
        pass
    return parts


# ────────────────────────────────────────────────────────────────────
#  ACCESSORIES: dormers, chimneys, skylights
# ────────────────────────────────────────────────────────────────────
def _dormer(cx, ey, face_dir, slope_pitch, base_z, color,
            w=1.15, h=1.05, depth=1.25, axis="y"):
    """Small gabled dormer poking out of a roof slope.
    axis="y": sits on a ±Y eave line (ey is that y, cx the position along it,
              face_dir=+1 faces +Y).
    axis="x": sits on a ±X eave line (ey is that x, cx the position along it,
              face_dir=+1 faces +X)."""
    parts = []
    t = np.tan(np.radians(slope_pitch))
    inset = depth * 0.55
    zc = base_z + inset * t + 0.25
    # build in a local frame: window face at y=0, body RECESSED into the
    # roof (toward -Y*face_dir) so the dormer sits ON the slope instead
    # of hovering past the eave line.
    body = trimesh.creation.box(extents=(w, depth, h))
    body.apply_translation([0, -face_dir * (depth / 2 - 0.05), zc])
    parts.append(_colored(body, WALL_COLOR))
    # window, proud of the dormer face
    win = trimesh.creation.box(extents=(w * 0.55, 0.06, h * 0.55))
    win.apply_translation([0, face_dir * 0.09, zc])
    parts.append(_colored(win, GLASS_COLOR))
    # mini gable cap (prism ridge natively along Y = out of the roof face)
    prof = _gable_profile(w + 0.3, (w / 2) * np.tan(np.radians(slope_pitch * 0.9)), 0.08)
    cap = _prism_from_profile(prof, depth + 0.3, color)
    cap.apply_translation([0, -(depth + 0.3) / 2, 0])
    cap.apply_transform(trimesh.transformations.rotation_matrix(
        0 if face_dir > 0 else np.pi, [0, 0, 1]))
    cap.apply_translation([0, -face_dir * (depth / 2 - 0.05), zc + h / 2 - 0.04])
    parts.append(cap)
    # move the whole dormer to its eave: rotate local +Y onto +X if needed
    T = np.eye(4)
    if axis == "x":
        T = trimesh.transformations.rotation_matrix(-np.pi / 2, [0, 0, 1])
        T[:3, 3] = [ey, cx, 0]
    else:
        T[:3, 3] = [cx, ey, 0]
    for m in parts:
        m.apply_transform(T)
    return parts


def _chimney(cx, cy, top_z, color=CHIMNEY_COLOR, size=0.55):
    parts = []
    body = trimesh.creation.box(extents=(size, size, top_z + 0.9))
    body.apply_translation([cx, cy, (top_z + 0.9) / 2])
    parts.append(_colored(body, color))
    cap = trimesh.creation.box(extents=(size + 0.18, size + 0.18, 0.10))
    cap.apply_translation([cx, cy, top_z + 0.95])
    parts.append(_colored(cap, [90, 90, 95, 255]))
    return parts


def _skylight(cx, cy, z, w=0.9, d=1.3):
    frame = trimesh.creation.box(extents=(w, d, 0.16))
    frame.apply_translation([cx, cy, z + 0.08])
    glass = trimesh.creation.box(extents=(w * 0.8, d * 0.8, 0.06))
    glass.apply_translation([cx, cy, z + 0.19])
    return [_colored(frame, [70, 70, 75, 255]), _colored(glass, GLASS_COLOR)]


# ════════════════════════════════════════════════════════════════════
#  4. TOP-LEVEL GENERATION
# ════════════════════════════════════════════════════════════════════
def _coverage_gap(parts, poly, wall_h, res=96, margin=0.45):
    """Fraction of the footprint interior left unroofed. Uses the same
    z-buffer rasterizer as the diffusion bridge; anything below the wall
    top means rain gets in — the reconstruction failed there."""
    meshes = [m for m in parts if isinstance(m, trimesh.Trimesh)]
    if not meshes:
        return 1.0
    inner = poly.buffer(-margin, join_style=2)
    if inner.is_empty:
        return 0.0
    x0, y0, x1, y1 = poly.bounds
    hm = rasterize_roof_heightmap(meshes, (x0 - 0.5, y0 - 0.5,
                                           x1 + 0.5, y1 + 0.5), res=res)
    xs = np.linspace(x0 - 0.5, x1 + 0.5, res)
    ys = np.linspace(y0 - 0.5, y1 + 0.5, res)
    total = uncovered = 0
    for j, y in enumerate(ys):
        for i, x in enumerate(xs):
            if inner.contains(Point(x, y)):
                total += 1
                if hm[j, i] < wall_h + 0.02:
                    uncovered += 1
    return uncovered / max(total, 1)


def generate_roof(walls, params, scale=0.01, wall_h=3.0):
    """Main entry point.  `params` comes from the AI designer
    (roof_ai.design_roof or ask_gemini.get_roof_parameters).
    Returns (list_of_meshes, info_dict)."""
    poly = extract_footprint(walls, scale)
    if poly is None:
        return [], {}

    style    = params.get("roof_style", "gable")
    pitch    = float(np.clip(params.get("pitch_angle", 30), 4, 75))
    overhang = float(np.clip(params.get("overhang", 0.45), 0.15, 1.0))
    seed     = params.get("seed")
    rng      = np.random.default_rng(seed)
    mat      = params.get("material")
    if mat not in ROOF_MATERIALS:
        mat = rng.choice(STYLE_MATERIALS.get(style, ["asphalt-dark"]))
    color = ROOF_MATERIALS[mat]

    m = footprint_metrics(poly)
    parts, ridge_h = [], 2.0
    base_z = wall_h

    if style == "composite":
        # RAG-retrieved multi-zone composition (roof_ai.design_roof_rag)
        zones = params.get("zones", [])
        parts, ridge_h = gen_composite(poly, zones, base_z, mat, rng)

    elif style in ("gable", "saltbox", "gambrel"):
        prof = "gambrel" if style == "gambrel" else "gable"
        shift = float(rng.uniform(0.25, 0.45)) * rng.choice([-1, 1]) \
                if style == "saltbox" else 0.0
        wings = decompose_wings(poly) if m["convexity"] < 0.92 else [m["bounds"]]
        for rect in wings:
            p, rh = gen_gable_wing(rect, base_z, pitch, overhang, color,
                                   ridge_shift=shift, profile=prof)
            parts += p
            ridge_h = max(ridge_h, rh)

    elif style == "cross-gable":
        wings = decompose_wings(poly)
        if len(wings) == 1:      # rectangular plan → synthesise a cross wing
            x0, y0, x1, y1 = wings[0]
            w, d = x1 - x0, y1 - y0
            cw = min(w, d) * rng.uniform(0.42, 0.55)
            cx = rng.uniform(x0 + cw, x1 - cw) if w > d else (x0 + x1) / 2
            cy = (y0 + y1) / 2 if w > d else rng.uniform(y0 + cw, y1 - cw)
            if w > d:
                wings.append((cx - cw / 2, y0 - rng.uniform(0.0, 0.6),
                              cx + cw / 2, y1 + rng.uniform(0.4, 1.2)))
            else:
                wings.append((x0 - rng.uniform(0.0, 0.6), cy - cw / 2,
                              x1 + rng.uniform(0.4, 1.2), cy + cw / 2))
        for rect in wings:
            p, rh = gen_gable_wing(rect, base_z, pitch, overhang, color)
            parts += p
            ridge_h = max(ridge_h, rh)

    elif style in ("hip", "pyramid"):
        parts += gen_hip(poly, base_z, pitch, overhang, color)
        ridge_h = (min(m["width"], m["depth"]) / 2 + overhang) * np.tan(np.radians(pitch))

    elif style == "dutch-gable":
        parts += gen_dutch_gable(poly, base_z, pitch, overhang, color)
        ridge_h = (min(m["width"], m["depth"]) / 2 + overhang) * np.tan(np.radians(pitch))

    elif style == "mansard":
        parts += gen_mansard(poly, base_z, color)
        ridge_h = 2.2

    elif style == "butterfly":
        parts += gen_butterfly(poly, base_z, max(6, min(pitch, 16)), overhang, color)
        ridge_h = 1.2

    elif style == "skillion":
        parts += gen_skillion(poly, base_z, max(6, min(pitch, 22)), overhang,
                              color, rng=rng)
        ridge_h = m["width"] * np.tan(np.radians(min(pitch, 22)))

    else:  # flat-modern & anything unknown
        parts += gen_flat_modern(poly, base_z, color)
        ridge_h = 0.8

    # ── self-check: no reconstruction may leave the footprint open ──
    # (composition bugs, degenerate zones, bad wing decompositions).
    # A leaky roof is rebuilt as a distance-field hip, which is
    # watertight for ANY footprint by construction.
    repaired = False
    if params.get("self_check", True) and parts:
        gap = _coverage_gap(parts, poly, wall_h)
        if gap > 0.03:
            print(f"⚠️ Roof self-check: {gap:.1%} of the footprint was "
                  f"unroofed → rebuilt as safe hip.")
            safe_pitch = float(np.clip(pitch, 18, 30))
            parts = gen_hip(poly, base_z, safe_pitch, overhang, color)
            ridge_h = (min(m["width"], m["depth"]) / 2 + overhang) * \
                np.tan(np.radians(safe_pitch))
            repaired = True

    # ── accessories ────────────────────────────────────────────────
    x0, y0, x1, y1 = m["bounds"]
    if params.get("has_dormers") and not repaired and \
            style in ("gable", "gambrel", "saltbox", "cross-gable", "mansard"):
        n = int(np.clip(params.get("dormer_count", rng.integers(1, 3)), 1, 3))
        along_x = m["width"] >= m["depth"]
        up = 0.55            # window face this far in from the eave,
        zlift = up * np.tan(np.radians(pitch))   # seated on the slope
        for k in range(n):
            frac = (k + 1) / (n + 1)
            if along_x:
                parts += _dormer(x0 + frac * (x1 - x0), y1 - up, +1, pitch,
                                 base_z + 0.30 + zlift, color)
            else:
                parts += _dormer(y0 + frac * (y1 - y0), x1 - up, +1, pitch,
                                 base_z + 0.30 + zlift, color, axis="x")

    if params.get("has_chimney") and style not in ("butterfly", "flat-modern"):
        cxy = poly.representative_point()
        jx = float(rng.uniform(-0.18, 0.18)) * m["width"]
        parts += _chimney(float(np.clip(cxy.x + jx, x0 + 1, x1 - 1)),
                          float(cxy.y), base_z + ridge_h)

    if params.get("has_skylight") and style in ("flat-modern", "skillion", "butterfly"):
        cxy = poly.representative_point()
        parts += _skylight(cxy.x, cxy.y, base_z + 0.25)

    info = {"style": style, "material": mat, "pitch": pitch,
            "overhang": overhang, "ridge_height": ridge_h,
            "wings": len(decompose_wings(poly)), "metrics": m,
            "repaired": repaired}
    return parts, info


# ════════════════════════════════════════════════════════════════════
#  5. COMPOSITE EXECUTOR  (used by the RAG designer, roof_ai.design_roof_rag)
#     Executes multi-zone roof compositions retrieved from the design
#     knowledge base: split-level skillions, clerestory bands, stacked
#     volumes, per-wing style mixes, sawtooth steps, ...
# ════════════════════════════════════════════════════════════════════
def _resolve_region(poly, wings, region):
    """Turn a symbolic region spec into an actual footprint sub-polygon."""
    x0, y0, x1, y1 = poly.bounds
    w, d = x1 - x0, y1 - y0
    rtype = region.get("type", "full")
    if rtype == "full":
        return poly
    if rtype == "wing":
        i = region.get("index", 0)
        if i < len(wings):
            wx0, wy0, wx1, wy1 = wings[i]
            zp = poly.intersection(shp_box(wx0 - 0.01, wy0 - 0.01,
                                           wx1 + 0.01, wy1 + 0.01))
        else:  # plan has fewer wings than the recipe expects → split halves
            f0, f1 = (0.0, 0.5) if i == 0 else (0.5, 1.0)
            return _resolve_region(poly, wings,
                                   dict(type="split", axis="long", f0=f0, f1=f1))
        if zp.is_empty:
            return None
        if isinstance(zp, MultiPolygon):
            zp = max(zp.geoms, key=lambda g: g.area)
        return zp
    if rtype == "split":
        axis = region.get("axis", "long")
        if axis == "long":
            axis = "x" if w >= d else "y"
        elif axis == "short":
            axis = "y" if w >= d else "x"
        f0, f1 = region.get("f0", 0.0), region.get("f1", 0.5)
        if axis == "x":
            cut = shp_box(x0 + f0 * w, y0 - 5, x0 + f1 * w, y1 + 5)
        else:
            cut = shp_box(x0 - 5, y0 + f0 * d, x1 + 5, y0 + f1 * d)
        zp = poly.intersection(cut)
        if zp.is_empty:
            return None
        if isinstance(zp, MultiPolygon):
            zp = max(zp.geoms, key=lambda g: g.area)
        return zp
    return poly


def _resolve_direction(dir_spec, poly):
    """'+long' / '-short' / '+x' ... → concrete '+x'/'-x'/'+y'/'-y'."""
    if dir_spec in ("+x", "-x", "+y", "-y"):
        return dir_spec
    x0, y0, x1, y1 = poly.bounds
    long_is_x = (x1 - x0) >= (y1 - y0)
    sign = dir_spec[0] if dir_spec and dir_spec[0] in "+-" else "+"
    axis = dir_spec.lstrip("+-") if dir_spec else "long"
    if axis == "long":
        return sign + ("x" if long_is_x else "y")
    return sign + ("y" if long_is_x else "x")


def gen_skillion_directed(poly, base_z, pitch, overhang, color,
                          direction="+y", fascia=0.18, footprint=None,
                          raised=False, posts="auto", porch=None,
                          soffit=True):
    """Single sloped plane. Beyond the bare wedge this now builds the
    structure that makes it read as architecture, not a floating shell:
      · soffit  — timber ceiling layer under the whole plane
      · posts   — pillars under the high edge whenever the plane floats
                  (raised clerestory zone, deep overhang, porch bay)
      · porch   — optional roof extension past one side, held by posts
    """
    fp = footprint if footprint is not None else poly
    p = poly.buffer(overhang, join_style=2)
    porch_edge = None
    if porch:
        porch_edge = _resolve_direction(porch.get("side", "-y"), fp)
        p = _directional_extend(p, porch_edge, float(porch.get("depth", 1.8)))
    x0, y0, x1, y1 = p.bounds
    t = np.tan(np.radians(pitch))
    fn = {"+x": lambda x, y: (x - x0) * t, "-x": lambda x, y: (x1 - x) * t,
          "+y": lambda x, y: (y - y0) * t, "-y": lambda x, y: (y1 - y) * t}[direction]
    parts = [_heightfield_roof(p, fn, base_z, fascia, color)]
    if soffit:
        parts += _soffit_plate(p, base_z)
    edges = []
    if posts == "auto":
        # the high edge is the side the plane rises toward
        if raised or porch is not None or overhang >= 0.5:
            edges.append(direction)
    elif posts:
        edges = [_resolve_direction(e, fp) for e in posts]
    if porch_edge and porch_edge not in edges:
        edges.append(porch_edge)
    for e in dict.fromkeys(edges):
        parts += _posts_along_edge(p, e, base_z + 0.08, footprint=fp)
    return parts


def _riser_band(zp, base_z, h, clerestory=False, wall_frac=0.30):
    """Perimeter band under a raised zone. Lower part is wall; if the
    recipe asks for a clerestory, the upper part is a glass band —
    the signature light strip of modern split-level roofs."""
    parts = []
    try:
        ring = zp.difference(zp.buffer(-0.14, join_style=2))
        if clerestory and h > 0.45:
            wall_h = max(0.18, h * wall_frac)
            wall = trimesh.creation.extrude_polygon(ring, height=wall_h)
            wall.apply_translation([0, 0, base_z])
            parts.append(_colored(wall, WALL_COLOR))
            glass = trimesh.creation.extrude_polygon(
                zp.difference(zp.buffer(-0.08, join_style=2)),
                height=h - wall_h)
            glass.apply_translation([0, 0, base_z + wall_h])
            parts.append(_colored(glass, GLASS_COLOR))
            # slim mullions
            mull = trimesh.creation.extrude_polygon(ring, height=0.05)
            mull.apply_translation([0, 0, base_z + h - 0.05])
            parts.append(_colored(mull, [60, 60, 65, 255]))
        else:
            band = trimesh.creation.extrude_polygon(ring, height=h)
            band.apply_translation([0, 0, base_z])
            parts.append(_colored(band, WALL_COLOR))
    except Exception:
        pass
    return parts


def gen_composite(poly, zones, base_z, default_material, rng):
    """Execute a multi-zone composition from the knowledge base."""
    wings = decompose_wings(poly)
    parts, max_top = [], 0.6
    for zspec in zones:
        zp = _resolve_region(poly, wings, zspec.get("region", {"type": "full"}))
        if zp is None or zp.area < 2.5:
            continue
        style = zspec.get("style", "flat")
        pitch = float(zspec.get("pitch", 14))
        ovh = float(zspec.get("overhang", 0.35))
        h_off = float(zspec.get("h_offset", 0.0))
        mat = zspec.get("material") or default_material
        color = ROOF_MATERIALS.get(mat, ROOF_MATERIALS["metal-seam"])
        z0 = base_z + h_off
        zm = footprint_metrics(zp)

        if h_off > 0.05:
            parts += _riser_band(zp, base_z - 0.15, h_off + 0.15,
                                 clerestory=bool(zspec.get("clerestory")))

        if style == "skillion":
            # direction MUST resolve against the full footprint: split
            # zones flip aspect, so "+short" measured on the zone itself
            # produced perpendicular planes with an open wedge into the
            # house (the hollow-rake artefact).
            d = _resolve_direction(zspec.get("direction", "+short"), poly)
            parts += gen_skillion_directed(
                zp, z0, pitch, ovh, color, d, footprint=poly,
                raised=h_off > 0.05, posts=zspec.get("posts", "auto"),
                porch=zspec.get("porch"))
            top = min(zm["width"], zm["depth"]) * np.tan(np.radians(pitch))
        elif style == "butterfly":
            parts += gen_butterfly(zp, z0, pitch, ovh, color)
            top = 0.9
        elif style == "flat":
            if zspec.get("parapet", True):
                parts += gen_flat_modern(zp, z0, color,
                                         parapet_h=0.5, overhang=ovh)
            else:
                pbuf = zp.buffer(ovh, join_style=2)
                porch = zspec.get("porch")
                if porch:
                    pbuf = _directional_extend(
                        pbuf, _resolve_direction(porch.get("side", "-y"), poly),
                        float(porch.get("depth", 1.8)))
                slab = trimesh.creation.extrude_polygon(pbuf, height=0.22)
                slab.apply_translation([0, 0, z0])
                parts.append(_colored(slab, color))
                parts += _soffit_plate(pbuf, z0)
                pspec = zspec.get("posts")
                edges = [_resolve_direction(e, poly) for e in pspec] \
                    if isinstance(pspec, (list, tuple)) else []
                if porch:
                    edges.append(_resolve_direction(porch.get("side", "-y"),
                                                    poly))
                for e in dict.fromkeys(edges):
                    parts += _posts_along_edge(pbuf, e, z0 + 0.08,
                                               footprint=poly)
            top = 0.75
        elif style in ("gable", "gambrel", "saltbox"):
            prof = "gambrel" if style == "gambrel" else "gable"
            shift = 0.35 * rng.choice([-1, 1]) if style == "saltbox" else 0.0
            p2, rh = gen_gable_wing(zm["bounds"], z0, pitch, ovh, color,
                                    ridge_shift=shift, profile=prof)
            parts += p2
            top = rh
        elif style in ("hip", "pyramid"):
            parts += gen_hip(zp, z0, pitch, ovh, color)
            top = (min(zm["width"], zm["depth"]) / 2 + ovh) * \
                  np.tan(np.radians(pitch))
        elif style == "dutch-gable":
            parts += gen_dutch_gable(zp, z0, pitch, ovh, color)
            top = (min(zm["width"], zm["depth"]) / 2) * np.tan(np.radians(pitch))
        elif style == "mansard":
            parts += gen_mansard(zp, z0, color)
            top = 2.2
        else:
            parts += gen_flat_modern(zp, z0, color)
            top = 0.75
        max_top = max(max_top, h_off + top)
    return parts, max_top


# ════════════════════════════════════════════════════════════════════
#  6. HEIGHTMAP → MESH  (bridge for the learned diffusion generator)
# ════════════════════════════════════════════════════════════════════
def mesh_from_heightmap(hm, mask, bounds, base_z=3.0, color=None,
                        smooth_sigma=1.0):
    """Convert a (H, W) roof heightmap in metres + binary footprint mask
    into a closed roof mesh registered onto the building.
    This is how a trained diffusion model's output enters the pipeline."""
    from scipy.ndimage import gaussian_filter
    hm = np.asarray(hm, dtype=float)
    mask = np.asarray(mask) > 0.5
    if smooth_sigma:
        hm = gaussian_filter(hm, smooth_sigma)
    H, W = hm.shape
    x0, y0, x1, y1 = bounds
    xs = np.linspace(x0, x1, W)
    ys = np.linspace(y0, y1, H)

    idx = -np.ones((H, W), dtype=int)
    verts = []
    for j in range(H):
        for i in range(W):
            if mask[j, i]:
                idx[j, i] = len(verts)
                verts.append([xs[i], ys[j], base_z + 0.12 + max(hm[j, i], 0)])
    top_faces = []
    for j in range(H - 1):
        for i in range(W - 1):
            a, b = idx[j, i], idx[j, i + 1]
            c, d = idx[j + 1, i], idx[j + 1, i + 1]
            if min(a, b, c, d) >= 0:
                top_faces += [[a, b, d], [a, d, c]]
    verts = np.array(verts, dtype=float)
    nv = len(verts)
    bot = verts.copy()
    bot[:, 2] = base_z
    faces = np.array(top_faces, dtype=np.int64)
    all_v = np.vstack([verts, bot])
    all_f = [faces, faces[:, ::-1] + nv]
    # rim
    ecount = {}
    for tri in faces:
        for a, b in ((tri[0], tri[1]), (tri[1], tri[2]), (tri[2], tri[0])):
            ecount[(min(a, b), max(a, b))] = ecount.get((min(a, b), max(a, b)), 0) + 1
    side = []
    for tri in faces:
        for a, b in ((tri[0], tri[1]), (tri[1], tri[2]), (tri[2], tri[0])):
            if ecount[(min(a, b), max(a, b))] == 1:
                side += [[a, b, b + nv], [a, b + nv, a + nv]]
    all_f.append(np.array(side, dtype=np.int64))
    mesh = trimesh.Trimesh(vertices=all_v, faces=np.vstack(all_f), process=True)
    return _colored(mesh, color or ROOF_MATERIALS["asphalt-gray"])


def rasterize_roof_heightmap(meshes, bounds, res=128):
    """Inverse bridge: numpy z-buffer rasterizer turning a procedural
    roof (list of trimesh meshes) into a (res, res) heightmap above the
    wall top — used to mass-produce synthetic diffusion training data."""
    x0, y0, x1, y1 = bounds
    hm = np.zeros((res, res), dtype=float)
    sx = (res - 1) / max(x1 - x0, 1e-6)
    sy = (res - 1) / max(y1 - y0, 1e-6)
    for mesh in meshes:
        if not isinstance(mesh, trimesh.Trimesh):
            continue
        tris = mesh.vertices[mesh.faces]
        for t in tris:
            px = (t[:, 0] - x0) * sx
            py = (t[:, 1] - y0) * sy
            iy0, iy1 = int(max(py.min(), 0)), int(min(py.max(), res - 1)) + 1
            ix0, ix1 = int(max(px.min(), 0)), int(min(px.max(), res - 1)) + 1
            if ix1 <= ix0 or iy1 <= iy0:
                continue
            gx, gy = np.meshgrid(np.arange(ix0, ix1), np.arange(iy0, iy1))
            # barycentric containment
            d = ((py[1] - py[2]) * (px[0] - px[2]) +
                 (px[2] - px[1]) * (py[0] - py[2]))
            if abs(d) < 1e-9:
                continue
            l1 = ((py[1] - py[2]) * (gx - px[2]) + (px[2] - px[1]) * (gy - py[2])) / d
            l2 = ((py[2] - py[0]) * (gx - px[2]) + (px[0] - px[2]) * (gy - py[2])) / d
            l3 = 1 - l1 - l2
            inside = (l1 >= -1e-6) & (l2 >= -1e-6) & (l3 >= -1e-6)
            z = l1 * t[0, 2] + l2 * t[1, 2] + l3 * t[2, 2]
            sub = hm[iy0:iy1, ix0:ix1]
            np.maximum(sub, np.where(inside, z, 0), out=sub)
    return hm
